name: ng_bind
description: Two-way input binders for Angular Dart. Alternative to NgModel. Does not depend on angular_components. Does not need a form.
version: 1.0.2
homepage: https://github.com/tejainece/ng_bind
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  angular: ^5.3.1

dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.5.0
  build_test: ^0.10.3
  build_web_compilers: ^2.1.0
  pedantic: ^1.7.0
  test: ^1.6.0
